# Generated by Django 4.1 on 2022-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_age', models.IntegerField()),
                ('pet_size', models.CharField(choices=[('Pe', 'Pequeño'), ('Me', 'Mediano'), ('Gr', 'Grande')], max_length=50)),
                ('pet_gender', models.CharField(max_length=50)),
                ('pet_description', models.CharField(max_length=400)),
                ('pet_picture', models.ImageField(blank=True, upload_to='uploads/')),
                ('pet_publication', models.DateTimeField(verbose_name='date published')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_lastname', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=150)),
                ('owner_phonenumber', models.IntegerField()),
            ],
        ),
    ]
